# fly.toml app configuration file generated for remember-it-memory-app on 2023-05-18T16:33:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remember-it-memory-app"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
